/**
 * Generates supabase/seed.sql from the typed local catalogue so the database
 * and the development seed never drift. `npm run db:seed:sql`
 */
import { localCatalogue } from '../src/data/catalogue'
import { PART_CATEGORY_META } from '../src/data/catalogue'

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v) && v.every((x) => typeof x === 'string')) return `array[${v.map(q).join(',')}]::text[]`
  if (typeof v === 'object') return `${q(JSON.stringify(v))}::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}
const row = (table: string, obj: Record<string, unknown>) =>
  `insert into public.${table} (${Object.keys(obj).join(', ')}) values (${Object.values(obj).map(q).join(', ')}) on conflict do nothing;`

const out: string[] = ['-- GENERATED by scripts/generate-seed.ts — do not edit by hand.', 'begin;']
const { bikes, colours, options, parts, showcase, services } = localCatalogue

Object.values(PART_CATEGORY_META).forEach((c, i) => out.push(row('part_categories', { id: c.id, label: c.label, descriptor: c.descriptor, sort_order: i })))
bikes.forEach((b, i) =>
  out.push(
    row('bikes', {
      id: b.id, slug: b.slug, brand: b.brand, model: b.model, name: b.name, year: b.year, variant: b.variant, thumbnail: b.thumbnail, status: b.status, base_price: b.basePrice,
      summary: b.summary, preview_image: b.previewImage, silhouette: b.silhouette, model3d: b.model3d,
      default_colour_id: b.defaultColourId, camera: b.camera, sort_order: i,
    }),
  ),
)
for (const b of bikes)
  b.slots.forEach((s, i) =>
    out.push(
      row('bike_slots', {
        bike_id: b.id, id: s.id, category: s.category, label: s.label, default_option_id: s.defaultOptionId,
        optional: !!s.optional, hotspot: b.hotspots.find((h) => h.slot === s.id)?.position, sort_order: i,
      }),
    ),
  )
colours.forEach((c, i) =>
  out.push(row('bike_colours', { id: c.id, bike_id: c.bikeId, name: c.name, swatch: c.swatch, material: c.material, price_delta: c.priceDelta, status: c.status, sort_order: i })),
)
parts.forEach((p) =>
  out.push(
    row('parts', {
      id: p.id, slug: p.slug, sku: p.sku, name: p.name, brand: p.brand, category: p.category, summary: p.summary,
      description: p.description, price: p.price, currency: p.currency, material: p.material, finish: p.finish,
      installation_notes: p.installationNotes, stock: p.stock, status: p.status, images: p.images,
    }),
  ),
)
for (const p of parts) for (const b of p.compatibleBikeIds) out.push(row('bike_compatibility', { part_id: p.id, bike_id: b }))
options.forEach((o, i) =>
  out.push(
    row('build_options', {
      id: o.id, compatible_bike_ids: o.compatibleBikeIds, affected_nodes: o.affectedNodes, slot_id: o.slot, category: o.category, name: o.name, descriptor: o.descriptor,
      price_delta: o.priceDelta, status: o.status, model_asset: o.modelAsset, material_config: o.materialConfig,
      preview_asset: o.previewAsset, requires: o.requires ?? [], excludes: o.excludes ?? [], part_id: o.partId, sort_order: i,
    }),
  ),
)
showcase.forEach((s) =>
  out.push(row('showcase_builds', { id: s.id, number: s.number, name: s.name, bike_id: s.bikeId, style: s.style, summary: s.summary, image: s.image, silhouette: s.silhouette, tone: s.tone, preset: s.preset })),
)
services.forEach((s, i) => out.push(row('services', { id: s.id, name: s.name, kicker: s.kicker, summary: s.summary, includes: s.includes, pitch: s.pitch ?? null, image: s.image ?? null, sort_order: i })))
out.push('commit;')
console.log(out.join('\n'))
